TYPEWRITTEN_PROMPT_LAYOUT="pure_verbose"
TYPEWRITTEN_SYMBOL="❱"
TYPEWRITTEN_ARROW_SYMBOL="->"
TYPEWRITTEN_RELATIVE_PATH="adaptive"
TYPEWRITTEN_CURSOR="beam"
TYPEWRITTEN_RIGHT_PROMPT_PREFIX=""
TYPEWRITTEN_LEFT_PROMPT_PREFIX_FUNCTION=(date +" %H:%M")
TYPEWRITTEN_COLORS=""
