#!/usr/bin/env sh

desc Used to monitor status notifier, systray
cmd dbus-monitor

desc Used to monitor file system changes
cmd inotifywait

desc Used to set wallpaper
cmd swww

desc Used to get sway workspaces information
cmd swaymsg

desc Used to retrieve XDG user directories
cmd xdg-user-dir

desc JSON parser for some scripts
cmd jq

