#!/usr/bin/env sh

desc Plugins fetch
cmd git


desc Builds telescope fzf
desca Builds Treesitter parsers
cmd make
cmd gcc


desc Used by Mason
desca Used by CodeCompanion to enable RAG
opt curl


desc Used by GitSigns
opt git


desc Used to run some LSP
opt node
opt python

