#!/usr/bin/env sh

req_cmd nvim "core editor" &&
req_cmd git "plugins fetcher" &&

req_cmd make "build treesitter parsers" &&
req_cmd cc "build treesitter parsers" &&

opt_cmd fzf "used with fzf-lua"
opt_cmd node "run some lsp servers and tools"
opt_cmd python "run some lsp servers and tools"

