return {
    file = {
        readonly = '󰌾',
        modified = '',
    },

    git = {
        -- Change type
        added     = '',
        deleted   = '󰆴',
        modified  = '',
        renamed   = '󰁕',

        -- Status type
        untracked = '',
        ignored   = '󰈅',
        unstaged  = '󰄱',
        staged    = '',
        conflict  = '',
    },

    diagnostics = {
        hint = '󰌵',
        info = '',
        warn = '󰉀',
        error = '',
    },

    debug = {
        rejectedpoint = '',
        breakpoint = '',
        condpoint = '',
        logpoint = '',
        stopped = '',
    },

    kinds = {
        Array         = '󰅪',
        Boolean       = '󰨙',
        Class         = '󰠱',
        Codeium       = '󰘦',
        Color         = '󰏘',
        Control       = '',
        Collapsed     = '',
        Constant      = '󰏿',
        Constructor   = '',
        Copilot       = '',
        Enum          = '󰒻',
        EnumMember    = '',
        Event         = '',
        Field         = '',
        -- Field         = '',
        File          = '󰈙',
        Folder        = '',
        Function      = '󰊕',
        Interface     = '',
        Key           = '󰌋',
        Keyword       = '',
        Method        = '󰊕',
        Module        = '',
        Namespace     = '󰦮',
        Null          = '󰟢',
        Number        = '󰎠',
        Object        = '󰅩',
        Operator      = '󰆕',
        Package       = '󰏖',
        Property      = '󰜢',
        Reference     = '',
        Snippet       = '',
        String        = '',
        Struct        = '󰆼',
        TabNine       = '󰏚',
        Text          = '',
        TypeParameter = '',
        Unit          = '',
        -- Unit = '',
        Value         = '',
        Variable      = '',
    },
}
