vim9script

if has('unix')
    import './xdg.vim' as xdg
endif

import './options.vim'
import './autocmd.vim'
import './keymaps.vim'

# Running in GUI mode
if has('gui_running')
    import './gui_options.vim'
endif

# Enable syntax highlight
syntax enable

# Enable file type detection
filetype plugin indent on

# Enable under curly
if empty(&t_Cs) || empty(&t_Ce)
    &t_Cs = "\e[4:3m"
    &t_Ce = "\e[4:0m"
endif

# Set different cursors for different modes
&t_SI = "\e[5 q"
&t_SR = "\e[3 q"
&t_EI = "\e[1 q"

if empty($MYVIMRC)
    $MYVIMRC = expand('<sfile>:p')
endif

#############################
####     COLORSCHEME     ####
#############################
silent! packadd! gruvbox
g:gruvbox_italic = 1
g:gruvbox_contrast_dark = 'hard'
g:gruvbox_hls_cursor = 'aqua'
g:gruvbox_sign_column = 'bg0'
g:gruvbox_italicize_strings = 1
g:gruvbox_invert_signs = 0
g:gruvbox_improved_strings = 1
g:gruvbox_improved_warnings = 1
g:gruvbox_guisp_fallback = 'fg'
silent! colorscheme gruvbox

silent! packadd! everforest
g:everforest_show_eob = 0
g:everforest_background = 'hard'
g:everforest_ui_contrast = 'high'
g:everforest_enable_italic = 1
g:everforest_spell_foreground = 'colored'
g:everforest_better_performance = 1
g:everforest_disable_terminal_colors = 1
#silent! colorscheme everforest

silent! packadd! rosepine
#silent! colorscheme rosepine_moon

#############################
####       PLUGINS       ####
#############################
def PackInit(): void
    packadd minpac

    call minpac#init({ package_name: 'minpac' })
    call minpac#add('k-takata/minpac', { type: 'opt' })

    call minpac#init({ package_name: 'packages' })
    ## Colors and syntax highlight
    call minpac#add('elkowar/yuck.vim')
    call minpac#add('sheerun/vim-polyglot')
    call minpac#add('sainnhe/everforest', { type: 'opt' })
    call minpac#add('morhetz/gruvbox', { type: 'opt' })
    call minpac#add('rose-pine/vim', { type: 'opt', name: 'rosepine' })

    ## Eye candy
    call minpac#add('ryanoasis/vim-devicons')
    call minpac#add('itchyny/lightline.vim')

    ## File browser
    call minpac#add('preservim/nerdtree')
    call minpac#add('xuyuanp/nerdtree-git-plugin')

    ## Auto closing
    call minpac#add('raimondi/delimitmate')
    call minpac#add('tpope/vim-endwise')

    ## Formatting
    call minpac#add('editorconfig/editorconfig-vim')
    call minpac#add('mattn/emmet-vim')

    ## Language server and Linter
    call minpac#add('yegappan/lsp')
    call minpac#add('dense-analysis/ale')

    ## Snippets
    call minpac#add('hrsh7th/vim-vsnip')
    call minpac#add('hrsh7th/vim-vsnip-integ')
    call minpac#add('rafamadriz/friendly-snippets')

    ## Git
    call minpac#add('airblade/vim-gitgutter')
    call minpac#add('tpope/vim-fugitive')

    ## Utilities
    call minpac#add('tpope/vim-surround')
    call minpac#add('tpope/vim-repeat')
enddef

command! PackUpdate source $MYVIMRC | call PackInit() | call minpac#update()
command! PackClean  source $MYVIMRC | call PackInit() | call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()

## Plugins configuration
# NERDTree and NERDTreeGitStatus
runtime plugins/nerdtree.vim

# GitGutter
runtime plugins/gitgutter.vim

# delimitMate and vim-endwise
runtime plugins/delimitmate.vim

# Lsp & Linter
runtime plugins/lsp.vim
runtime plugins/ale.vim

# Vsnip
runtime plugins/vsnip.vim

# lightline.vim
runtime plugins/lightline.vim

