## XDG Base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"

export PATH="$HOME/.local/bin:$PATH"


## XDG Runtime directory
if [ -z "$XDG_RUNTIME_DIR" ]; then
    # Check if running inside Termux, if so, use the Termux prefix
    if [ -n "$(printenv | grep -i "termux")" ]; then
        export XDG_RUNTIME_DIR="$PREFIX/tmp/$USER-runtime"
    else
        export XDG_RUNTIME_DIR="/tmp/$USER-runtime"
    fi

    if [ ! -d "$XDG_RUNTIME_DIR" ]; then
        mkdir -pm 0700 "$XDG_RUNTIME_DIR"
    fi
fi


## DBUS session address
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus
fi


## Zsh environment variables
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZDATADIR="$XDG_DATA_HOME/zsh"

export HISTFILE="$ZDATADIR/zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

export ZLE_RPROMPT_INDENT="0"


## Starship config path
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/config.toml"

## Common variables
export EDITOR=nvim
export VISUAL=nvim


# .NET
export DOTNET_ROOT=$HOME/.dotnet
export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools


# Go
[ -z "$GOPATH" ] && export GOPATH="${HOME}/go"
[ -z "$GOBIN" ] && export GOBIN="${GOPATH}/bin"
export PATH=$PATH:$GOROOT/bin:$GOBIN


# Ollama setup
export OLLAMA_KEEP_ALIVE=10m
export OLLAMA_KV_CACHE_TYPE=q8_0
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_MAX_LOADED_MODELS=1

