#
# XDG Base Directories
#

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

export XDG_DATA_DIRS="${XDG_DATA_DIRS:-$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share}"


#
# XDG Runtime Directory
#

if [[ -z "$XDG_RUNTIME_DIR" ]]; then
    if [[ -n "$TERMUX_VERSION" && -n "$PREFIX" ]]; then
        export XDG_RUNTIME_DIR="$PREFIX/tmp/runtime-$UID"
    else
        export XDG_RUNTIME_DIR="/tmp/runtime-$UID"
    fi

    if [[ ! -d "$XDG_RUNTIME_DIR" ]]; then
        mkdir -m 0700 -p "$XDG_RUNTIME_DIR"
    fi
fi


#
# Zsh
#

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZDATADIR="$XDG_DATA_HOME/zsh"

export HISTFILE="$ZDATADIR/zhistory"
export HISTSIZE=10000
export SAVEHIST=10000

export ZPROMPT_POS="UP"
export ZLE_RPROMPT_INDENT=0


#
# Applications
#

export EDITOR="nvim"
export VISUAL="$EDITOR"

export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/config.toml"


#
# .NET
#

export DOTNET_ROOT="$HOME/.dotnet"
export DOTNET_CLI_TELEMETRY_OPTOUT=true


#
# Go
#

export GOPATH="${GOPATH:-$HOME/go}"
export GOBIN="${GOBIN:-$GOPATH/bin}"


#
# Android
#

export ANDROID_HOME="$XDG_DATA_HOME/android/sdk"
export ANDROID_USER_HOME="$XDG_CONFIG_HOME/android"
export ANDROID_AVD_HOME="$XDG_DATA_HOME/android/avd"


#
# Ollama
#

export OLLAMA_KEEP_ALIVE=-1
export OLLAMA_KV_CACHE_TYPE="q8_0"
export OLLAMA_FLASH_ATTENTION=1
export OLLAMA_MAX_LOADED_MODELS=1
export OLLAMA_NUM_PARALLEL=1


#
# PATH
#

typeset -U path PATH

path=(
    "$HOME/.local/bin"

    "$DOTNET_ROOT"
    "$DOTNET_ROOT/tools"

    "$GOBIN"

    "$ANDROID_HOME/cmdline-tools/latest/bin"
    "$ANDROID_HOME/platform-tools"
    "$ANDROID_HOME/emulator"

    $path
)

export PATH
