## XDG Base directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_HOME="$HOME/.local/share"

export PATH="$HOME/.local/bin:$PATH"


## XDG Runtime directory
if [ -z "$XDG_RUNTIME_DIR" ]; then
    # Check if running inside Termux, if so, use the Termux prefix
    if [ -n "$(printenv | grep -i "termux")" ]; then
        export XDG_RUNTIME_DIR="$PREFIX/tmp/$USER-runtime"
    else
        export XDG_RUNTIME_DIR="/tmp/$USER-runtime"
    fi

    if [ ! -d "$XDG_RUNTIME_DIR" ]; then
        mkdir -pm 0700 "$XDG_RUNTIME_DIR"
    fi
fi


## DBUS session address
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus


## Zsh environment variables
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZDATADIR="$XDG_DATA_HOME/zsh"

export HISTFILE="$ZDATADIR/zhistory"
export HISTSIZE=1000
export SAVEHIST=1000

export ZLE_RPROMPT_INDENT="0"


## Common variables
export EDITOR=nvim
export VISUAL=nvim

