" Compatibility
if &compatible
	set nocompatible
endif
set cpoptions+=EgnW

""
""" VIM XDG base directories
""""
source $XDG_CONFIG_HOME/vim/xdg.vim

""
"""  Options
""""
runtime! options.vim

""
"""  Keymaps
""""
runtime! keymaps.vim

""
"""  Autocmds
""""
runtime! autocmds.vim

""
"""  Colorschemes
""""
let g:polyglot_disabled = [ 'sensible', 'ftdetect' ]

packadd! onedark.vim
packadd! everforest

let g:everforest_background = 'hard'
let g:everforest_disable_italic_comment = 1
let g:everforest_sign_column_background = 'none'
let g:everforest_ui_contrast = 'high'
let g:everforest_show_eob = 0
let g:everforest_diagnostic_text_highlight = 1
let g:everforest_better_performance = 1

silent! colorscheme onedark

""
""" Plugins
""""
let g:snips_author = 'Jonatha Gabriel'

let g:lexima_map_escape = 'jk'
let g:lexima_accept_pum_with_enter = 1

let NERDCommentWholeLinesInVMode = 1
let NERDRemoveExtraSpaces = 1
let NERDSpaceDelims = 1
let NERDTrimTrailingWhitespace = 1

let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '~'
let g:gitgutter_sign_removed = '_'
let g:gitgutter_sign_removed_first_line = '‾'
let g:gitgutter_sign_removed_above_and_below = '_¯'
let g:gitgutter_sign_modified_removed = '~_'
let g:gitgutter_sign_allow_clobber = 0
let g:gitgutter_sign_priority = 9
let g:gitgutter_preview_win_floating = 1
let g:gitgutter_use_location_list = 1

let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cursor_column = 0
let g:syntastic_error_symbol = ''
let g:syntastic_warning_symbol = ''
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_jump = 3
let g:syntastic_auto_loc_list = 1
let g:syntastic_loc_list_height = 10
let g:syntastic_stl_format = "%E{" . g:syntastic_error_symbol . " %fe}"
let g:syntastic_stl_format .= "%B{, }"
let g:syntastic_stl_format .= "%W{" . g:syntastic_warning_symbol . " %fw}"

function! SyntasticCheckHook(errors) abort
	let l:max_size = g:syntastic_loc_list_height

	if !empty(a:errors)
		let g:syntastic_loc_list_height = min([len(a:errors), l:max_size])
	endif

	call lightline#update()
endfunction

let lightline = {}
let lightline.colorscheme = g:colors_name
let lightline.separator = { 'left': '', 'right': '' }
let lightline.subseparator = { 'left': '', 'right': '', }
let lightline.component = { 'lineinfo': '%3l  %02c ' }
let lightline.component_type = { 'syntastic': 'error' }
let lightline.component_expand = { 'syntastic': 'SyntasticStatuslineFlag' }
let lightline.component_function = {
\	'filename': 'LightlineFilename',
\	'fileinfo': 'LightlineFileinfo'
\}

let lightline.active = {
\	'left': [[ 'mode', 'paste' ], [ 'filename' ]],
\	'right': [[ 'syntastic', 'lineinfo' ], [ 'percent' ], [ 'fileinfo' ]]
\}

let lightline.inactive = {
\	'left': [[ 'filename' ]],
\	'right': [[ 'lineinfo' ], [ 'percent' ], [ 'fileinfo' ]]
\}

let lightline.mode_map = {
\	'n' : 'N',
\	'i' : 'I',
\	'R' : 'R',
\	'v' : 'V',
\	'V' : 'VL',
\	"\<C-v>": 'VB',
\	'c' : 'C',
\	's' : 'S',
\	'S' : 'SL',
\	"\<C-s>": 'SB',
\	't': 'T',
\}

function! LightlineFilename() abort
	let l:modified = &modified ? ' ' : ''
	let l:filename = expand('%:t') ==# '' ? '[No Name]' : expand('%:t')
	let l:readonly = &readonly ? ' ' : ''

	return l:modified . l:filename . l:readonly
endfunction

function! LightlineFileinfo() abort
	let l:filetype = &filetype ==# '' ? 'no ft' : &filetype . ' '
	\	. WebDevIconsGetFileTypeSymbol()

	let l:fileformat = &fileformat . ' ' . WebDevIconsGetFileFormatSymbol()
	let l:fileencoding = &fileencoding ==# '' ? &encoding : &fileencoding

	let l:info = [ l:filetype, l:fileencoding, l:fileformat ]
	return lightline#concatenate(l:info, 1)
endfunction

