" Compatibility
if &compatible
	set nocompatible
endif
set cpoptions+=EgnW

""
"""  Options
""""
runtime! options.vim

""
"""  Keymaps
""""
runtime! keymaps.vim

""
"""  Autocmds
""""
augroup HighlightSearch
	autocmd!
	autocmd CmdLineEnter /,? set hlsearch
	autocmd CmdLineLeave /,? set nohlsearch
augroup END

""
"""  Colorschemes
""""
let g:polyglot_disabled = [ 'sensible' ]

let g:gruvbox_italic = 1
let g:gruvbox_contrast_dark = 'hard'
let g:gruvbox_hls_cursor = 'red'
let g:gruvbox_sign_column = 'none'
let g:gruvbox_invert_selection = 0
let g:gruvbox_invert_indent_guides = 1
let g:gruvbox_improved_strings = 1
let g:gruvbox_improved_warnings = 1
silent! colorscheme gruvbox

let g:tokyonight_style = 'night'
let g:tokyonight_enable_italic = 0
let g:tokyonight_disable_italic_comment = 1
"silent! colorscheme tokyonight

""
""" Plugins
""""
let g:lexima_map_escape = 'jk'
let g:lexima_accept_pum_with_enter = 1

let NERDCommentWholeLinesInVMode = 1
let NERDRemoveExtraSpaces = 1
let NERDSpaceDelims = 1
let NERDTrimTrailingWhitespace = 1

