#!/usr/bin/env sh

###################
### Variables
export HLWM="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"

###################
### Helper functions

hc() {
    herbstclient "$@"
}

get_value() {
    echo $(echo $1 | cut -d' ' -f$2)
}

load_colors() {
    export foreground="$(xrdb -get foreground)"
    export background="$(xrdb -get background)"
    export transparent="#00000000"

    for color_num in $(seq 0 15); do
        eval "export color$color_num=\$(xrdb -get color$color_num)"
    done
}


###################
### Miscellaneous
hc lock
hc emit_hook reload


###################
### Keybindings

# Remove all existing keybindings
hc keyunbind --all

# Modifiers
Alt=Mod1
Super=Mod4

#########
### Miscellaneous
hc keybind $Super-Shift-q quit
hc keybind $Super-Shift-r reload
hc keybind $Super-Shift-c close

hc keybind $Super-Return  spawn "${TERMINAL:-st}"

#########
### Monitor

# Focus
hc keybind $Super-period cycle_monitor +1
hc keybind $Super-comma  cycle_monitor -1

# Move windows
hc keybind $Super-Shift-period shift_to_monitor +1
hc keybind $Super-Shift-comma  shift_to_monitor -1

#########
### Window

# Focus
hc keybind $Super-h     focus left
hc keybind $Super-j     focus down
hc keybind $Super-k     focus up
hc keybind $Super-l     focus right

hc keybind $Super-i jumpto urgent
hc keybind $Super-m jumpto last-minimized

hc keybind $Super-c cycle +1

# Move
hc keybind $Super-Shift-h     shift left
hc keybind $Super-Shift-j     shift down
hc keybind $Super-Shift-k     shift up
hc keybind $Super-Shift-l     shift right

# Resize
resizestep=0.02
hc keybind $Super-Control-h       resize left +$resizestep
hc keybind $Super-Control-j       resize down +$resizestep
hc keybind $Super-Control-k       resize up +$resizestep
hc keybind $Super-Control-l       resize right +$resizestep

# Attributes
hc keybind $Super-Shift-s set_attr clients.focus.floating toggle
hc keybind $Super-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Super-Shift-m set_attr clients.focus.minimized true

#########
### Layout

# Mode
hc keybind $Super-s floating toggle
hc keybind $Super-f fullscreen toggle
hc keybind $Super-p pseudotile toggle

# Remove frame
hc keybind $Super-r       remove

# Split frame
hc keybind $Super-u       split   bottom  0.5
hc keybind $Super-o       split   right   0.5

# Frame layout
hc keybind $Super-$Alt-g set_layout grid
hc keybind $Super-$Alt-h set_layout horizontal
hc keybind $Super-$Alt-m set_layout max
hc keybind $Super-$Alt-v set_layout vertical

#########
### Tags

tag_names="α β γ δ ε ζ η"
tag_keys="1 2 3 4 5 6 7"

hc rename default "$(get_value "$tag_names" 1)" || true
for i in $(seq 1 $(echo "$tag_names" | wc -w)); do
    hc add "$(get_value "$tag_names" $i)"

    key="$(get_value "$tag_keys" $i)"
    hc keybind "$Super-$key"       use_index  "$(($i - 1))"
    hc keybind "$Super-Shift-$key" move_index "$(($i - 1))"
done


###################
### Mouse binds

# Remove all binds
hc mouseunbind --all

hc mousebind $Super-Button1 move
hc mousebind $Super-Button2 zoom
hc mousebind $Super-Button3 resize


###################
### Settings

load_colors

# Frame settings
hc set frame_active_opacity         70
hc set frame_normal_opacity         70
hc set frame_bg_active_color        $color3
hc set frame_bg_normal_color        $transparent
hc set frame_bg_transparent         on
hc set frame_border_width           0
hc set frame_border_active_color    $color3
hc set frame_border_normal_color    $color4
hc set frame_padding                -5
hc set frame_transparent_width      5

# Only show frame decoration on empty focused frames
hc watch tags.focus.frame_count
pgrep -f $HLWM/frame_decoration.sh || $HLWM/frame_decoration.sh &

# General settings
hc set auto_detect_monitors         on
hc set default_frame_layout         max
hc set hide_covered_windows         on
hc set mouse_recenter_gap           20
hc set raise_on_focus               on
hc set smart_window_surroundings    on
hc set tree_style                   '╾│ ├└╼─┐'
hc set update_dragged_clients       on
hc set window_gap                   5

# Set frame layout to default frame layout
hc substitute LAYOUT settings.default_frame_layout       \
    foreach TAG tags.by-name                             \
        sprintf ATTRIBUTE "%c.tiling.root.algorithm" TAG \
            set_attr ATTRIBUTE LAYOUT


###################
### Theme

# Reset theme
hc set_attr theme.floating.reset true
hc set_attr theme.minimal.reset true
hc set_attr theme.tiling.reset true

# Miscellaneous
hc set_attr theme.background_color $background

# Title in all modes
for mode in floating minimal tiling; do
    hc set_attr theme.$mode.title_align center
    hc set_attr theme.$mode.title_color $foreground
    hc set_attr theme.$mode.title_depth 0
    hc set_attr theme.$mode.title_font ":pixelsize=1"
    hc set_attr theme.$mode.title_height 20
    hc set_attr theme.$mode.title_when always
done

#########
### Floating
hc set_attr theme.floating.border_width 2

#########
### Minimal

hc set_attr theme.minimal.outer_width 5
hc set_attr theme.minimal.outer_color $transparent
hc set_attr theme.minimal.tab_outer_width 0

# Active
hc set_attr theme.minimal.active.color $color3
hc set_attr theme.minimal.active.tab_color $color3

# Normal
hc set_attr theme.minimal.normal.color $color4
hc set_attr theme.minimal.normal.tab_color $color4

# Urgent
hc set_attr theme.minimal.urgent.color $color5
hc set_attr theme.minimal.urgent.tab_color $color5

#########
### Tiling

hc set_attr theme.tiling.active.outer_width 5
hc set_attr theme.tiling.active.outer_color $transparent
hc set_attr theme.tiling.active.tab_outer_width 0

#########
### Floating and tilling

# Active
hc set_attr theme.active.color $color3
hc set_attr theme.active.tab_color $color3

# Normal
hc set_attr theme.normal.color $color4
hc set_attr theme.normal.tab_color $color4

# Urgent
hc set_attr theme.urgent.color $color5
hc set_attr theme.urgent.tab_color $color5


###################
### Rules

# Remove all rules
hc unrule --all

hc rule --focus=on
hc rule --fixedsize --floating=on
hc rule --floatplacement=smart

hc rule --windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' --floating=on
hc rule --windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' --manage=off

hc rule --windowtype='_NET_WM_WINDOW_TYPE_SPLASH' --floatplacement=center
hc rule --windowtype='_NET_WM_WINDOW_TYPE_DIALOG' --focus=on


###################
### More miscellaneous
hc unlock
hc detect_monitors

