#!/usr/bin/env sh

root_dir=$(cd $(dirname $0); pwd)

## Start syncthing daemon
if [ -z "$(pgrep -f syncthing)" ]; then
    syncthing --no-browser --no-restart --no-default-folder \
        --logfile=$HOME/.cache/syncthing.log &
fi

## Start dbus user session
dbus="dbus-daemon --session --address=$DBUS_SESSION_BUS_ADDRESS"
if [ -z "$(pgrep -f "$dbus")" ]; then
    $dbus &
fi


## Start pipewire
if [ -z "$(pgrep -f pipewire)" ]; then
    # With this PipeWire will automatic start pipewire-pulse and WirePlumber
    # if the PipeWire configuration is installed
    pipewire &
fi


## Start notification server
if [ -z "$(pgrep -f dunst)" ]; then
   dunst &
fi


## Start swww daemon (wallpaper setter)
if [ -z "$(pgrep -f swww-daemon)" ]; then
    swww-daemon &
fi


## Start eww (widgets)
if [ -z "$(pgrep -f eww)" ]; then
    $root_dir/eww_init
fi
sh $root_dir/scripter color-reloader eww &


## Change cursor
dconf write /org/gnome/desktop/interface/cursor-theme "'default'"
dconf write /org/gnome/desktop/interface/cursor-size 28


## Start sway idle
if [ -z "$(pgrep -f swayidle)" ]; then
    swayidle -w \
        timeout 90 'swaymsg "output * dpms off"' \
            resume 'swaymsg "output * dpms on"' \
        timeout 150 'exec zzz' &
fi


## Start foot server and always restart if closed
(
    if [ -z "$(pgrep -f 'foot --server')" ]; then
        while true; do
            foot --server --override shell="$root_dir/scripter color-reloader foot" &
            wait $!
        done
    fi
) &


## Start battery status notifier
sh $root_dir/scripter battery notify


## Start color color temperature adjuster
sh $root_dir/scripter color-temperature run &


## Start color re-loader
sh $root_dir/scripter color-reloader \
    rio \
    nvim \
    tmux \
    zsh \
    starship \
    btop \
    cava \
    bat \
    git \
    notification \
    wm \
    rofi &

