#!/usr/bin/env sh

root=$(cd $(dirname $0); pwd)

## Time
while true; do
    eww ping >/dev/null
    [ $? -ne 0 ] && continue


    eww update hour="$(date +"%H")"
    eww update minute="$(date +"%M")"

    eww update uptime="$(TZ=UTC date -d@$(cut -d" " -f1 /proc/uptime) +"{ \"days\": \"%-j\", \"hours\": \"%-H\", \"mins\": \"%02M\" }")"

    sleep 1
done &


## Indicators
while true; do
    eww ping >/dev/null
    [ $? -ne 0 ] && continue


    eww update wifi="$($root/scripter network wifi status)"
    eww update ethernet="$($root/scripter network ethernet status)"
    eww update bluetooth="$($root/scripter network bluetooth status)"
    eww update multimedia="$($root/scripter multimedia status)"
    eww update notification="$($root/scripter notification status)"
    eww update brightness="$($root/scripter brightness get)"

    eww update battery="$($root/scripter battery status)"

    sleep 0.1
done &


## Run notification listener
## to gets raw image data of notification if any
$root/scripter --binary notifications


## Initialize eww
eww daemon
sleep 1
eww open-many bar corner-top corner-bottom

# vim: ft=bash
