#!/usr/bin/env sh

req_cmd inotifywait "watch theme changes" &&

opt_cmd bat "reload bat and git colors"
opt_cmd nvim "reload neovim colros"
opt_cmd tmux "reload tmux colors"
opt_cmd mmsg "reload mango colors"
opt_cmd zsh "reload starship colors"

