#!/usr/bin/env sh

# Log functions
error() { echo "\033[31m[Error]\033[0m $1"; }
warn() { echo "\033[33m[Warning]\033[0m $1"; }
info() { echo "\033[32m[Info]\033[0m $1"; }

# Helper functions
can_call_api() {
    timefile="$1"
    now=$(date +%s)

    [ ! -f "$timefile" ] && echo 0 > "$timefile"

    last=$(cat "$timefile")
    [ -z "$last" ] && last=0

    diff=$(( now - last ))

    if [ "$diff" -ge 600 ]; then
        echo "$now" > "$timefile"
        return 0
    else
        return 1
    fi
}

str_contains() {
    case $1 in
        *"$2"*)
            return 0
            ;;

        *)
            return 1
            ;;
    esac
}


# Signals
SIGHUP=1
SIGINT=2
SIGQUIT=3
SIGABRT=4
SIGKILL=9
SIGTERM=15

# vim ft=bash
