#!/usr/bin/env sh

# Log functions
error() { printf '\033[31m[Error]\033[0m %s\n'   "$*" >&2; }
warn()  { printf '\033[33m[Warning]\033[0m %s\n' "$*" >&2; }
info()  { printf '\033[32m[Info]\033[0m %s\n'    "$*" >&2; }

# Helper functions
get_dotfiles_root() {
    test_dir=$(cd "$(dirname "$1")" && pwd)

    while [ "$test_dir" != "/" ]; do
        [ -x "$test_dir/dotfile" ] && echo "$test_dir" && return 0
        test_dir=$(dirname "$test_dir")
    done

    error "Can't find dotfiles root from: $1"
    return 1
}

can_call_api() {
    timefile="$1"
    now=$(date +%s)

    [ ! -f "$timefile" ] && echo 0 > "$timefile"

    last=$(cat "$timefile")
    [ -z "$last" ] && last=0

    diff=$(( now - last ))

    if [ "$diff" -ge 600 ]; then
        echo "$now" > "$timefile"
        return 0
    else
        return 1
    fi
}

str_contains() {
    case $1 in
        *"$2"*) return 0 ;;
        *) return 1 ;;
    esac
}

# vim: ft=sh
