#!/usr/bin/env sh

# Scripts directory root
root=$(cd "$(dirname "$0")" && pwd)

if [ ! -f "$root/_common" ]; then
    printf '\033[31m[Error]\033[0m _common not found at %s\n' "$root/_common" >&2
    exit 1
fi
. "$root/_common"

## Cache
cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/scripter"
mkdir -p "$cache_dir"

_run_script() {
    script="$1"
    shift

    if [ ! -e "$root/$script" ]; then
        error "Can't find script '$script' to run!"
        exit 1
    fi

    if [ ! -x "$root/$script" ]; then
        error "Script '$script' hasn't executable permission!"
        exit 1
    fi

    script_cache="$cache_dir/$script"
    mkdir -p "$script_cache"

    (
        export SCRIPT_CACHE_DIR="$script_cache"

        . "$root/_common"

        if [ -f "$root/_keys" ]; then
            . "$root/_keys"
        fi

        . "$root/$script"
    )

    # WARNING: Do not remove!
    #
    # Never should be echoed after script execution. Immediately exit the runner
    # script!
    #
    # If some script call another script (e.g. weather calls location) through
    # this script (_scripter) the output of this script (_scripter) will be
    # passed to caller script alongside with callee script output.
    exit $?
}

_run_script "$@"

# vim: ft=sh
