#!/usr/bin/env sh

run() {
    match=""
    if [ "$1" = "--match" ] || [ "$1" = "-m" ]; then
        shift
        match="$1"
        shift
    fi

    cmd="$1"; shift
    bin=$(basename "$cmd")

    if ! command -v "$cmd" >/dev/null 2>&1; then
        warn "autostart: command not found: '$cmd'"
        return 1
    fi

    if [ -n "$match" ]; then
        if pgrep -f "$match" >/dev/null 2>&1; then
            warn "autostart: '$match' already running, skipping"
            return 0
        fi
    else
        if pgrep -x "$bin" >/dev/null 2>&1; then
            warn "autostart: '$bin' already running, skipping"
            return 0
        fi
    fi

    info "autostart: starting '$bin $*'"
    "$cmd" "$@" &
}

## Start dbus user session
run --match "dbus-daemon --session" dbus-daemon --session --address="$DBUS_SESSION_BUS_ADDRESS"


## Start pipewire

# With this PipeWire will automatic start pipewire-pulse and WirePlumber
# if the PipeWire configuration is installed on setup
run pipewire


## Start notification server
run dunst


## Start foot server and always restart if closed
(
    if pgrep -f "foot --server" >/dev/null 2>&1; then
        warn "autostart: 'foot server' already running, skipping"
        exit 0
    fi

    stop_restart=0
    trap 'stop_restart=1' USR1

    info "autostart: starting 'foot server'"
    while true; do
        if [ -n "$WAYLAND_DISPLAY" ]; then
            foot --server &
            wait $!
            exit_code=$?

            [ "$stop_restart" -eq 1 ] \
                && info "autostart: 'foot server' restart stopped" \
                && break

            info "autostart: 'foot server' exited (code $exit_code), restarting..."
        else
            warn "autostart: 'WAYLAND_DISPLAY' not set, waiting..."
        fi

        sleep 2
    done
) &


## Start battery status notifier
sh "$root/_scripter" battery notify


## Start color temperature adjuster
sh "$root/_scripter" color-temperature run &


## Start color re-loader
sh "$root/_scripter" color-reloader \
    foot \
    nvim \
    tmux \
    starship \
    btop \
    cava \
    bat \
    git \
    wm &

# vim: ft=sh
