#!/usr/bin/env sh

case $1 in
    # TODO: include a --save and --restores option to save set value to later
    # be restored.
    set)
        signal="${2%%[0-9]*}"
        value="${2#"$signal"}"

        # For brightnessctl the minus signal should be at end of value and plus
        # signal must be at start but on this script all signal must be at start
        # of the value, so conversion is needed.
        #
        # E.g.:
        #   -50 or -50% -> 50- or 50%-
        #   +50 or +50% -> no conversion
        [ "$signal" = '+' ] && value=$signal$value
        [ "$signal" = '-' ] && value=$value$signal

        brightnessctl --class backlight set "$value" >/dev/null 2>&1
        ;;

    get)
        cur=$(brightnessctl --class backlight get)
        max=$(brightnessctl --class backlight max)

        echo "{ \"current\": \"$cur\", \"max\": \"$max\" }"
        ;;

    *)
        error "Unknown command '$1'!"
        exit 1
        ;;
esac

