#!/usr/bin/env sh

# Cache
cache_dir=$SCRIPT_CACHE_DIR

cache_time=$cache_dir/time
cache_json=$cache_dir/json

if [ -z "$cache_dir" ]; then
    exit 1
elif [ ! -d "$cache_dir" ]; then
    mkdir -p $cache_dir

    # Timestamp of last API call
    touch $cache_time

    # Last response API json
    touch $cache_json
fi


_get() {
    while true; do
        if can_call_api $cache_time; then
            json=$(curl -s http://ip-api.com/json)
            [ -n "$json" ] && echo "$json" > $cache_json
        else
            json=$(cat $cache_json)
        fi

        # Only output json when successfully fetch data
        echo $json
        break
    done
}


case $1 in
    city)
        _get | jq --raw-output '.city'
        ;;

    latitude|lat)
        _get | jq --raw-output '.lat'
        ;;

    longitude|lon)
        _get | jq --raw-output '.lon'
        ;;
esac

