#!/usr/bin/env sh

# Cache
cache_dir=$SCRIPT_CACHE_DIR
cache_last_notify_id=$cache_dir/last_notify_id
cache_last_notify_time=$cache_dir/last_notify_time

if [ ! -d "$cache_dir" ]; then
    mkdir -p "$cache_dir"

    echo 0 > $cache_last_notify_id
    echo 0 > $cache_last_notify_time
fi


_get_status() {
    mic_mute=0
    mic_volume=$(wpctl get-volume @DEFAULT_SOURCE@ | sed -ne 's/.*\([0-9]\.[0-9]\{2\}\).*/\1/p')

    speaker_mute=0
    speaker_volume=$(wpctl get-volume @DEFAULT_SINK@ | sed -ne 's/.*\([0-9]\.[0-9]\{2\}\).*/\1/p')

    if [ -n "$(wpctl get-volume @DEFAULT_SOURCE@ | sed -ne 's/.*\(MUTED\).*/\1/p')" ]; then
        mic_mute=1
    fi

    if [ -n "$(wpctl get-volume @DEFAULT_SINK@ | sed -ne 's/.*\(MUTED\).*/\1/p')" ]; then
        speaker_mute=1
    fi

    printf '{'

    # Speaker
    printf '"speaker": {'
    printf '"mute": %s,' $speaker_mute
    printf '"volume": %s' $speaker_volume
    printf '},'

    # Microphone
    printf '"microphone": {'
    printf '"mute": %s,' $mic_mute
    printf '"volume": %s' $mic_volume
    printf '}'

    printf '}\n'
}

_get_volume_icon() {
    volume=$1

    if [ $volume -le 33 ]; then
        icon=''
    elif [ $volume -le 66 ]; then
        icon=''
    else
        icon=''
    fi

    echo "<span font_desc='Phosphor-Fill' size='24pt'>$icon</span>"
}


cmd=$1
case $cmd in
    status)
        _get_status
        ;;

    speaker | mic)
        target="@DEFAULT_SINK@"
        if [ "$cmd" = 'mic' ]; then
            target="@DEFAULT_SOURCE@"
        fi

        subcmd=$2
        case $subcmd in
            set)
                # For wpctl all signals should be at end of value but on this
                # script all signal must be at start of the value, so conversion
                # is needed.
                signal=$(echo $3 | sed -ne 's/\([-|+]*\).*/\1/p')
                value=$(echo $3 | sed -ne 's/[^0-9]*\([0-9]*\).*/\1/p')
                percent=$(echo $3 | sed -ne 's/.*%/%/p')

                # Normalize
                int=$(( $value / 100 ))
                dec=$(( ${value}00 / 100 ))

                if [ ${#dec} -lt 2 ]; then
                    dec="0$dec"
                fi

                value=$int.$(echo $dec | sed -e 's/.\([0-2]\)\{2\}$/\1/')
                wpctl set-volume --limit 1.0 $target $value$percent$signal


                # Notify current volume value
                appname="scripter-multimedia"
                timeout=2000

                value=$(wpctl get-volume $target | sed -ne 's/.*\([0-9]\.[0-9]\{2\}\).*/\1/p')
                value=$(echo "$value" | jq --raw-output '(. * 100) | floor')

                time=$(cat $cache_last_notify_time)
                if [ $(( $(date +%s) - $time )) -gt $(( $timeout / 1000 )) ]; then
                    id=$(notify-send -p -h int:value:$value -a "$appname" -t $timeout "volume" "$(_get_volume_icon $value)")
                    echo $id > $cache_last_notify_id
                else
                    id=$(cat $cache_last_notify_id)
                    notify-send -r $id -h int:value:$value -a "$appname" -t $timeout "volume" "$(_get_volume_icon $value)"
                fi

                echo $(date +%s) > $cache_last_notify_time
                ;;

            get)
                mute=0
                volume=$(wpctl get-volume $target | sed -ne 's/.*\([0-9]\.[0-9]\{2\}\).*/\1/p')

                if [ -n "$(wpctl get-volume $target | sed -ne 's/.*\(MUTED\).*/\1/p')" ]; then
                    mute=1
                fi

                printf '{'
                printf '"mute": %s,' $mute
                printf '"volume": %s' $volume
                printf '}\n'
                ;;

            mute)
                wpctl set-mute $target toggle
                ;;

            *)
                error "Unknown command '$subcmd'!"
                exit 1
                ;;
        esac
        ;;

    *)
        error "Unknown command '$cmd'!"
        exit 1
        ;;
esac

