#!/usr/bin/env sh

# Cache
cache_dir=$SCRIPT_CACHE_DIR

cache_dir_wifi=$cache_dir/wifi
cache_wifi_power=$cache_dir_wifi/power
cache_wifi_quality=$cache_dir_wifi/quality

cache_dir_bluetooth=$cache_dir/bluetooth
cache_bluetooth_power=$cache_dir_bluetooth/power

if [ -z "$cache_dir" ]; then
    exit 1
elif [ ! -d "$cache_dir" ]; then
    mkdir -p $cache_dir
    mkdir -p $cache_dir_wifi
    mkdir -p $cache_dir_bluetooth

    # Bluetooth
    touch $cache_bluetooth_power

    # WiFi
    touch $cache_wifi_quality
    touch $cache_wifi_power

    for i in $(seq 1 5); do
        echo -50 >> $cache_wifi_quality
    done
fi


_net_check_connection() {
    for url in google.com duckduckgo.com wikipedia.org; do
        ping -c 1 $url 1>/dev/null
        if [ $? -eq 0 ]; then
            return 1
        fi
    done

    return 0
}

_net_get_info() {
    type=$1
    if [ "$type" = "wifi" ]; then
        interfaces=$(find /sys/class/net -name "wlan*" -or -name "wl*")
    elif [ "$type" = "ethernet" ]; then
        interfaces=$(find /sys/class/net -name "en*" -or -name "eth*")
    fi

    connected=0
    for net in $interfaces; do
        carrier=$(cat $net/carrier 2>/dev/null)
        operstate=$(cat $net/operstate)

        if [ -n "$carrier" ]; then
            connected=$carrier
        elif [ "$operstate" = "up" ]; then
            # Maybe this isn't needed, if interface is up carrier will never be
            # empty
            connected=1
        elif [ "$operstate" = "down" ]; then
            # This is when the interface is "soft" down, i.e., using ip link, in
            # this case the carrier will be empty
            connected=0
        elif [ "$operstate" = "unknown" ]; then
            # Maybe this isn't needed too, if interface operational state is
            # unknown carrier also will never be empty
            connected=$carrier
        fi

        # Stop at any connected interface
        if [ "$connected" = 1 ]; then
            break
        fi
    done

    # Immediately return if disconnected
    if [ "$connected" = 0 ]; then
        echo "{ \"enable\": \"$connected\", \"quality\": \"unknown\" }"
        return
    fi

    # Get connection quality
    if [ "$type" = "wifi" ]; then
        if [ -n "$(command -pv iwctl)" ]; then
            # Get WiFi name from iwd
            interface="$(iwctl device list | sed '1,4d' | cut -d' ' -f3)"
            iwctl_output="$(iwctl station $interface show)"

            name="$(echo "$iwctl_output" | sed '1,6d;8,$d;s/.*network\s*//;s/\s*$//')"
        elif [ -n "$(command -pv wpa_cli)" ]; then
            # Get WiFi name from wpa_supplicant
            name=$(wpa_cli status | tr '\n' ';' | cut -d';' -f4 | cut -d'=' -f2)
        else
            name=""
        fi

        _net_check_connection
        if [ $? -gt 0 ]; then
            if [ -n "$(command -pv iwctl)" ]; then
                # Get WiFi quality from iwd
                quality="$(echo "$iwctl_output" | sed '1,13d;15,$d;s/.*\(-[0-9]*\).*/\1/')"
            elif [ -n "$(command -pv wpa_cli)" ]; then
                # Get WiFi quality from wpa_supplicant
                quality=$(wpa_cli signal_poll | tr '\n' ';' | cut -d';' -f8 | cut -d'=' -f2)
            else
                # Get WiFi quality from Linux
                quality=$(cat /proc/net/wireless | sed -ne 's/.*\(-[0-9]\{2,4\}\)\..*/\1/p')
            fi

            # Update WiFi quality file
            sed -ie '1d' "$cache_wifi_quality"
            echo "$quality" >> $cache_wifi_quality

            # Calculate average WiFi quality
            sum=0
            count=0
            for value in $(cat $cache_wifi_quality); do
                sum=$(($sum + $value))
                count=$(( $count + 1 ))
            done
            quality=$(( $sum / $count ))

            if [ "$quality" -ge -50 ]; then
                quality=high
            elif [ "$quality" -ge -70 ]; then
                quality=good
            elif [ "$quality" -ge -89 ]; then
                quality=low
            else
                quality=bad
            fi
        else
            quality="noconnection"
        fi
    elif [ "$type" = "ethernet" ]; then
        _net_check_connection
        if [ $? -gt 0 ]; then
            quality="unkown"
        else
            quality="noconnection"
        fi
    fi

    printf '{'
    printf '"enable": %s,' $connected
    printf '"quality": "%s"' $quality
    if [ -n "$name" ]; then
        printf ','
        printf '"name": "%s"' "$name"
    fi
    printf '}\n'
}

_net_wifi_enabled() {
    cmd="$1"

    if [ -n "$(command -pv iwctl)" ]; then
        interface="$(iwctl device list | sed '1,4d' | cut -d' ' -f3)"
        iwctl device $interface set-property Powered $cmd
    elif [ -n "$(command -pv wpa_cli)" ]; then
        error "Not available to wpa_supplicant!"
        exit 1
    else
        error "Not available without some WiFi manager!"
        exit 1
    fi

    echo $cmd > $cache_wifi_power
}

_bl_get_info() {
    info=$(bluetoothctl show)

    if [ "$(echo $info | sed -ne 's/.*Powered: \([a-z]\{2,3\}\).*/\1/p')" = "yes" ]; then
        enable=1

        if [ -n "$(bluetoothctl devices Connected)" ]; then
            status="connected"
        else
            status="disconnected"
        fi

        echo "on" > $cache_bluetooth_power
    else
        enable=0
        status="unknown"

        echo "off" > $cache_bluetooth_power
    fi

    echo "{ \"enable\": \"$enable\", \"status\": \"$status\"}"
}


case $1 in
    wifi)
        case $2 in
            status)
                _net_get_info wifi
                ;;

            on | off | toggle)
                cmd=$2
                if [ "$cmd" = "toggle" ]; then
                    enable=$(cat $cache_wifi_power)
                    if [ "$enable" = "off" ]; then
                        cmd="on"
                    else
                        cmd="off"
                    fi
                fi

                _net_wifi_enabled $cmd
                ;;
        esac
        ;;

    ethernet)
        case $2 in
            status)
                _net_get_info ethernet
                ;;
        esac
        ;;

    bluetooth)
        case $2 in
            status)
                _bl_get_info
                ;;

            on | off | toggle)
                cmd=$2
                if [ "$cmd" = "toggle" ]; then
                    enable=$(cat $cache_bluetooth_power)
                    if [ "$enable" = "off" ]; then
                        cmd="on"
                    else
                        cmd="off"
                    fi
                fi

                bluetoothctl power $cmd >/dev/null
                echo $cmd > $cache_bluetooth_power
                ;;
        esac
        ;;
esac

