#!/usr/bin/env sh

cache_dir=$SCRIPT_CACHE_DIR

cache_time="$cache_dir/time"
cache_json="$cache_dir/json"

[ -n "$cache_dir" ] || exit 1

mkdir -p "$cache_dir"
touch "$cache_time" "$cache_json"

_get() {
    # NOTE: location script will block until it can fetch location data
    LAT=$(sh "$root/_scripter" location latitude)
    LON=$(sh "$root/_scripter" location longitude)

    url="https://wttr.in/${LAT},${LON}?format=j1"

    json=$(cat "$cache_json")
    if [ -z "$json" ]; then
        json=$(curl -fsSL "$url" | tee "$cache_json")
    elif can_call_api "$cache_time"; then
        json=$(curl -fsSL "$url" | tee "$cache_json")
    fi

    printf '%s\n' "$json"
}

case "$1" in
    temperature)
        _get | jq -r '.current_condition[0].temp_C'
        ;;

    description)
        _get | jq -r '.current_condition[0].weatherDesc[0].value'
        ;;

    icon)
        case "$(_get | jq -r '.current_condition[0].weatherCode')" in
            113) icon='󰖨' ;;  # Sunny

            116) icon='' ;;  # Partly cloudy
            119|122) icon='' ;;  # Cloudy / Overcast

            143|248|260) icon='' ;;  # Mist / Fog

            176|263|266|293|296|299|302|305|308|311|314|317|353|356|359)
                icon=''
                ;;

            179|182|185|227|230|281|284|320|323|326|329|332|335|338|350|362|365|368|371|374|377|392|395)
                icon=''
                ;;

            200|386|389)
                icon=''
                ;;

            *)
                icon='?'
                ;;
        esac

        printf '%s\n' "$icon"
        ;;
esac

