" Compatibility
if &compatible
  set nocompatible
endif
set cpoptions+=EgnW

""
""" Vim XDG base directories
""""
if empty($XDG_CONFIG_HOME)
  let g:xdg_vim_config = $HOME . '/.config'
else
  let g:xdg_vim_config = $XDG_CONFIG_HOME
endif

exe "source " . g:xdg_vim_config . '/vim/xdg.vim'

""
"""  Options
""""
runtime! options.vim

""
"""  Key maps
""""
runtime! keymaps.vim

""
"""  Auto commands
""""
runtime! autocmds.vim

""
"""  Color schemes
""""
runtime! colorschemes.vim

""
"""  Packages
""""
runtime! packages.vim

