[config]
# Nothing

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland'
output_path = '~/.cache/colors/hyprland.conf'

[templates.eww]
input_path = '~/.config/matugen/templates/eww'
output_path = '~/.config/eww/styles/colors.scss'

[templates.foot]
input_path = '~/.config/matugen/templates/foot'
output_path = '~/.cache/colors/foot.ini'

