#!/usr/bin/env sh

# Scripts directory root
root=$(cd $(dirname $0); pwd)

# Log function
error() { echo "\033[31m[Error]\033[0m $1"; }

# Helper function
_get_dotfiles_root() {
    test_dir=$(realpath $root)

    while [ "$test_dir" != "$HOME" ]; do
        if [ -x "$test_dir/dotfile" ]; then
            break
        fi

        test_dir=$(realpath $(dirname $test_dir))
    done

    if [ "$test_dir" != "$HOME" ]; then
        echo "$test_dir"
        return 0
    else
        echo ""
        return 1
    fi
}

# Try find scripts directory
dotfiles_root="$(_get_dotfiles_root)"
if [ $? -eq 1 ]; then
    error "Can't find dotfiles directory!"
    exit 1
else
    if [ "$1" = "--binary" -o "$1" = "-b" ]; then
        shift
        binary=$1
        shift

        $dotfiles_root/bin/$binary $@
    else
        sh $dotfiles_root/scripts/_scripter $@
    fi
fi

