##  ╔═╗┌┐┌┬┌┬┐┌─┐┌┬┐┬┌─┐┌┐┌┌─┐
##  ╠═╣│││││││├─┤ │ ││ ││││└─┐
##  ╩ ╩┘└┘┴┴ ┴┴ ┴ ┴ ┴└─┘┘└┘└─┘

animations = 1
animation_type_open=zoom
animation_type_close=fade

# vertical tag animation
tag_animation_direction = 0
