##  ╔═╗┌─┐┌─┐┌─┐┌─┐┬─┐┌─┐┌┐┌┌─┐┌─┐
##  ╠═╣├─┘├─┘├┤ ├─┤├┬┘├─┤││││  ├┤
##  ╩ ╩┴  ┴  └─┘┴ ┴┴└─┴ ┴┘└┘└─┘└─┘

# Border
borderpx = 2
border_radius = 20
no_radius_when_single = 0

# Gaps
smartgaps = 0
gappih = 15
gappiv = 15
gappoh = 30
gappov = 15

# Shadows
shadows = 1
layer_shadows = 1
shadow_only_floating = 0
shadows_size = 8
shadows_blur = 20
shadows_position_x = 10
shadows_position_y = 10
shadowscolor = 0x000000ff

# Cursor
cursor_theme = default
cursor_size = 28
