##  ╔╗ ┬┌┐┌┌┬┐┌─┐
##  ╠╩╗││││ ││└─┐
##  ╚═╝┴┘└┘─┴┘└─┘

##
## Programs
##

# terminal
bind = Super, Return, spawn, foot

# launcher
bind = Super, Space, spawn, qs ipc call launcher toggle


##
## Multimedia
##

# audio
bind = None, XF86AudioRaiseVolume, spawn, ~/.config/mango/scripter multimedia speaker set +5
bind = None, XF86AudioLowerVolume, spawn, ~/.config/mango/scripter multimedia speaker set -5
bind = None, XF86AudioMute, spawn, ~/.config/mango/scripter multimedia speaker mute

bind = None, XF86AudioMicMute, spawn, ~/.config/mango/scripter multimedia mic mute

# brightness
bind = None, XF86MonBrightnessUp, spawn, ~/.config/mango/scripter brightness screen set +5%
bind = None, XF86MonBrightnessDown, spawn, ~/.config/mango/scripter brightness screen set -5%


##
## Window
##

bind = Super, q, killclient

bind = Super, h, focusdir, left
bind = Super, j, focusdir, down
bind = Super, k, focusdir, up
bind = Super, l, focusdir, right

bind = Super + Shift, h, exchange_client, left
bind = Super + Shift, j, exchange_client, down
bind = Super + Shift, k, exchange_client, up
bind = Super + Shift, l, exchange_client, right


##
## Tags
##

# focus tag
bind = Super, 1, view, 1
bind = Super, 2, view, 2
bind = Super, 3, view, 3
bind = Super, 4, view, 4
bind = Super, 5, view, 5
bind = Super, 6, view, 6
bind = Super, 7, view, 7
bind = Super, 8, view, 8
bind = Super, 9, view, 9

bind = Super, u, viewtoleft
bind = Super, i, viewtoright

# move window to tag
bind = Super + Shift, 1, tag, 1
bind = Super + Shift, 2, tag, 2
bind = Super + Shift, 3, tag, 3
bind = Super + Shift, 4, tag, 4
bind = Super + Shift, 5, tag, 5
bind = Super + Shift, 6, tag, 6
bind = Super + Shift, 7, tag, 7
bind = Super + Shift, 8, tag, 8
bind = Super + Shift, 9, tag, 9

bind = Super + Shift, u, tagtoleft
bind = Super + Shift, i, tagtoright


##
## Monitor
##

bind = Super + Ctrl, h, focusmon, left
bind = Super + Ctrl, j, focusmon, down
bind = Super + Ctrl, k, focusmon, up
bind = Super + Ctrl, l, focusmon, right

bind = Super + Ctrl + Shift, h, tagmon, left
bind = Super + Ctrl + Shift, j, tagmon, down
bind = Super + Ctrl + Shift, k, tagmon, up
bind = Super + Ctrl + Shift, l, tagmon, right

# open monitors management panel
bind = Super, p, spawn, qs ipc call monitors toggle


##
## Layout
##

bind = Super, f, togglemaximizescreen
bind = Super + Shift, f, togglefullscreen
bind = Super, v, togglefloating

bind = Super, t, setlayout, tile
bind = Super, s, setlayout, scroller
bind = Super, g, setlayout, grid
bind = Super, n, switch_layout

bind = Super, e, set_proportion, 1.0
bind = Super, x, switch_proportion_preset

##
## Miscellaneous
##

# close
bind = Super + Shift, q, quit

# reload configuration
bind = Super, r, reload_config

bind = Alt, Tab, toggleoverview

# screenshot
bind = None, Print, spawn, ~/.config/mango/scripter screenshot screen
bind = Ctrl, Print, spawn, ~/.config/mango/scripter screenshot --clipboard screen
bind = Alt, Print, spawn, ~/.config/mango/scripter screenshot area
bind = Ctrl + Alt, Print, spawn, ~/.config/mango/scripter screenshot --clipboard area

# lock screen
bind = Super, b, spawn, qs ipc call lockscreen lock


##
## Mouse binds
##

mousebind = Super, btn_left, moveresize, curmove
mousebind = Super, btn_right, moveresize, curresize

axisbind = Super, Left, focusdir, left
axisbind = Super, Up, viewtoleft
axisbind = Super, Down, viewtoright
axisbind = Super, Right, focusdir, right

##
## Gestures
##

gesturebind = none, up, 4, toggleoverview
gesturebind = none, down, 4, toggleoverview
