##
##              ███╗   ███╗ █████╗ ███╗   ██╗ ██████╗  ██████╗
##              ████╗ ████║██╔══██╗████╗  ██║██╔════╝ ██╔═══██╗
##              ██╔████╔██║███████║██╔██╗ ██║██║  ███╗██║   ██║
##              ██║╚██╔╝██║██╔══██║██║╚██╗██║██║   ██║██║   ██║
##              ██║ ╚═╝ ██║██║  ██║██║ ╚████║╚██████╔╝╚██████╔╝
##              ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝  ╚═════╝
##
##               ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
##              ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
##              ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
##              ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
##              ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
##               ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
##

##  ╔═╗┌─┐┌┐┌┌─┐┬─┐┌─┐┬
##  ║ ╦├┤ │││├┤ ├┬┘├─┤│
##  ╚═╝└─┘┘└┘└─┘┴└─┴ ┴┴─┘

# environment variables
env = QT_QPA_PLATFORM, wayland
env = _JAVA_AWT_WM_NONREPARENTING, 1


##  ╔═╗┬ ┬┌┬┐┌─┐┌─┐┌┬┐┌─┐┬─┐┌┬┐
##  ╠═╣│ │ │ │ │└─┐ │ ├─┤├┬┘ │
##  ╩ ╩└─┘ ┴ └─┘└─┘ ┴ ┴ ┴┴└─ ┴

exec-once = ~/.config/mango/scripter autotart

##  ╔═╗┌─┐┬ ┬┬─┐┌─┐┌─┐┌─┐
##  ╚═╗│ ││ │├┬┘│  ├┤ └─┐
##  ╚═╝└─┘└─┘┴└─└─┘└─┘└─┘

source = ./input.conf
source = ./output.conf
source = ./binds.conf
source = ./layout.conf
source = ./appearance.conf
source = ./animations.conf
