##  ╦┌┐┌┌─┐┬ ┬┌┬┐
##  ║│││├─┘│ │ │
##  ╩┘└┘┴  └─┘ ┴

# keyboard
numlockon = 1
repeat_rate = 30
repeat_delay = 500
xkb_rules_layout = us,br
xkb_rules_variant = altgr-intl,
xkb_rules_options = grp:lalt_lshift_toggle

# touchpad
tap_to_click = 1
tap_and_drag = 1
drag_lock = 1
scroll_method = 1               # two-finger scrolling
click_method = 2                # clickfinger: the number of fingers determines which button is pressed
button_map = 0                  # 1/2/3 finger tap maps to left/right/middle
disable_while_typing = 1
middle_button_emulation = 1
trackpad_natural_scrolling = 1

# mouse
mouse_natural_scrolling = 0

# miscellaneous
focus_on_activate = 1
sloppyfocus = 1                 # focus follows the mouse
warpcursor = 1                  # warp the cursor to the window center when focus with keyboard
cursor_hide_timeout = 3
drag_corner = 4
drag_warp_cursor = 0
drag_tile_to_tile = 1           # allow dragging a tiled window onto another to swap their positions
