##  ╦  ┌─┐┬ ┬┌─┐┬ ┬┌┬┐
##  ║  ├─┤└┬┘│ ││ │ │
##  ╩═╝┴ ┴ ┴ └─┘└─┘ ┴

circle_layout = tile,scroller,grid

# Master
default_nmaster = 1
default_mfact = 0.65
new_is_master = 0

# Center Tile
center_master_overspread = 0
center_when_single_stack = 1

# Scroller
scroller_structs = 70
scroller_default_proportion = 0.5
scroller_default_proportion_single = 1.0
scroller_focus_center = 0
scroller_prefer_center = 1
scroller_prefer_overspread = 1
scroller_proportion_preset = 0.5, 1.0
scroller_ignore_proportion_single = 0
edge_scroller_pointer_focus = 0

# Overview
enable_hotarea = 1
hotarea_corner = 1
ov_tab_mode = 0
overviewgappi = 10
overviewgappo = 100
