##  ╦═╗┬ ┬┬  ┌─┐┌─┐
##  ╠╦╝│ ││  ├┤ └─┐
##  ╩╚═└─┘┴─┘└─┘└─┘

# Firefox picture-in-picture floating
windowrule = isfloating:1, appid:[fF]irefox, title:Picture-in-Picture
windowrule = width:800, height:480, appid:[fF]irefox, title:Picture-in-Picture
