#!/usr/bin/env sh

# Scripts directory root
root=$(cd "$(dirname "$0")" && pwd)

# Try find scripts directory
test_dir="$(realpath "$root")"
while [ "$test_dir" != "/" ]; do
    [ -x "$test_dir/dotfile" ] && break
    test_dir="$(realpath "$(dirname "$test_dir")")"
done

if [ ! -x "$test_dir/dotfile" ]; then
    printf '\033[31m[Error]\033[0m Can'\''t find dotfiles root!\n' >&2
    exit 1
fi

sh "$test_dir/scripts/_scripter" "$@"

# vim: ft=sh
