###############
# General
###############

allow-external-apps = true
default-working-directory = /data/data/com.termux/files/home
disable-terminal-session-change-toast = true
# hide-soft-keyboard-on-startup = true
# soft-keyboard-toggle-behaviour = enable/disable
terminal-onclick-url-open = true
terminal-transcript-rows = 5000
terminal-margin-horizontal = 0
terminal-margin-vertical = 0
volume-keys = volume

###############
# Fullscreen mode
###############

fullscreen = true
use-fullscreen-workaround = true

###############
# Cursor
###############

# Cursor rates: 0 - 2000
terminal-cursor-blink-rate = 250
# Cursor style: block, bar, underline.
terminal-cursor-style = underline

###############
# Extra keys
###############

# Styles: default, arrows-only, arrows-all, all and none
# extra-keys-style = default
# extra-keys-text-all-caps = true
# extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'], \
#               ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]

###############
# Colors/themes
###############

use-black-ui = true

###############
# HW keyboard shortcuts
###############

# disable-hardware-keyboard-shortcuts = true
shortcut.create-session = ctrl + 0
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 1
# shortcut.rename-session = ctrl + n

###############
# Bell key
###############

# Bell behaviour: vibrate, beep, ignore
bell-character = ignore

###############
# Back key
###############

# Back key value: escape, back
back-key=back

###############
# Keyboard issue workarounds
###############

# enforce-char-based-input = true
# ctrl-space-workaround = true

